### ISSUE TITLE
variables have no effect on settings.json

### ISSUE THREAD

**Issue by aristosv** [iPromKnight/zilean#85]
This is how I build the zilean container

```
  zilean:
    image: ipromknight/zilean
    container_name: zilean
    hostname: zilean
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Nicosia
      - Zilean__EnableDashboard=true
      - Zilean__Database__ConnectionString="Host=zilean-postgres;Database=zilean;Username=postgres;Password=postgres;"
    ports:
      - 8181:8181
    volumes:
      - zilean:/app/data

  zilean-postgres:
    image: postgres
    container_name: zilean-postgres
    hostname: zilean-postgres
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Nicosia
      - POSTGRES_DB=zilean
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - zilean-postgres:/var/lib/postgresql/data
```

But the "Zilean__EnableDashboard" and "Zilean__Database__ConnectionString" have no effect on "settings.json".

This is settings.json

```
{
  "Zilean": {
    "ApiKey": "df8e7479882345aab909d395f981c951f3a57072dda449e5a950faac8d8582d3",
    "FirstRun": true,
    "EnableDashboard": false,
    "Dmm": {
      "EnableScraping": true,
      "EnableEndpoint": true,
      "ScrapeSchedule": "0 * * * *",
      "MinimumReDownloadIntervalMinutes": 30,
      "MaxFilteredResults": 200,
      "MinimumScoreMatch": 0.85
    },
    "Torznab": {
      "EnableEndpoint": true
    },
    "Database": {
      "ConnectionString": "Host=postgres;Database=zilean;Username=postgres;Password=postgres;Include Error Detail=true;Timeout=30;CommandTimeout=3600;"
    },
```
